{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatchAvailability"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/adyenapplepayextensionprovisioning\/watchavailability"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/adyenapplepayextensionprovisioning\/watchavailability"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/objc(pl)NSObject","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/RemoteLibraryAvailability","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/s7CVarArgP","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/s28CustomDebugStringConvertibleP","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/s23CustomStringConvertibleP","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/SQ","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/SH","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/objc(pl)WCSessionDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/remoteLibraryIsAvailable()","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/session(_:activationDidCompleteWith:error:)","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/sessionDidBecomeInactive(_:)","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/sessionDidDeactivate(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatchAvailability"}],"title":"WatchAvailability","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@AdyenApplePayExtensionProvisioning@objc(cs)WatchAvailability","modules":[{"name":"AdyenApplePayExtensionProvisioning"}],"navigatorTitle":[{"kind":"identifier","text":"WatchAvailability"}]},"hierarchy":{"paths":[["doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning"]]},"references":{"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning":{"role":"collection","title":"AdyenApplePayExtensionProvisioning","abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning","kind":"symbol","type":"topic","url":"\/documentation\/adyenapplepayextensionprovisioning"},"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/RemoteLibraryAvailability":{"role":"symbol","title":"RemoteLibraryAvailability","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteLibraryAvailability"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/RemoteLibraryAvailability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RemoteLibraryAvailability"}],"url":"\/documentation\/adyenapplepayextensionprovisioning\/remotelibraryavailability"},"doc://adyen.AdyenApplePayExtensionProvisioning/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/SH"},"doc://adyen.AdyenApplePayExtensionProvisioning/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/s28CustomDebugStringConvertibleP"},"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/WatchAvailability/remoteLibraryIsAvailable()":{"role":"symbol","title":"remoteLibraryIsAvailable()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteLibraryIsAvailable"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/remoteLibraryIsAvailable()","kind":"symbol","type":"topic","url":"\/documentation\/adyenapplepayextensionprovisioning\/watchavailability\/remotelibraryisavailable()"},"doc://adyen.AdyenApplePayExtensionProvisioning/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/s7CVarArgP"},"doc://adyen.AdyenApplePayExtensionProvisioning/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/s23CustomStringConvertibleP"},"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/WatchAvailability/sessionDidBecomeInactive(_:)":{"role":"symbol","title":"sessionDidBecomeInactive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionDidBecomeInactive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WCSession","preciseIdentifier":"c:objc(cs)WCSession"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/sessionDidBecomeInactive(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionDidBecomeInactive:"}],"url":"\/documentation\/adyenapplepayextensionprovisioning\/watchavailability\/sessiondidbecomeinactive(_:)"},"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/WatchAvailability/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/adyenapplepayextensionprovisioning\/watchavailability\/init"},"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/WatchAvailability":{"role":"symbol","title":"WatchAvailability","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatchAvailability"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WatchAvailability"}],"url":"\/documentation\/adyenapplepayextensionprovisioning\/watchavailability"},"doc://adyen.AdyenApplePayExtensionProvisioning/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/objc(cs)NSObject"},"doc://adyen.AdyenApplePayExtensionProvisioning/objc(pl)WCSessionDelegate":{"type":"unresolvable","title":"WCSessionDelegate","identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/objc(pl)WCSessionDelegate"},"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/WatchAvailability/sessionDidDeactivate(_:)":{"role":"symbol","title":"sessionDidDeactivate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionDidDeactivate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WCSession","preciseIdentifier":"c:objc(cs)WCSession"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/sessionDidDeactivate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionDidDeactivate:"}],"url":"\/documentation\/adyenapplepayextensionprovisioning\/watchavailability\/sessiondiddeactivate(_:)"},"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/WatchAvailability/session(_:activationDidCompleteWith:error:)":{"role":"symbol","title":"session(_:activationDidCompleteWith:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WCSession","preciseIdentifier":"c:objc(cs)WCSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activationDidCompleteWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WCSessionActivationState","preciseIdentifier":"c:@E@WCSessionActivationState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/session(_:activationDidCompleteWith:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"session:activationDidCompleteWithState:error:"}],"url":"\/documentation\/adyenapplepayextensionprovisioning\/watchavailability\/session(_:activationdidcompletewith:error:)"},"doc://adyen.AdyenApplePayExtensionProvisioning/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/objc(pl)NSObject"},"doc://adyen.AdyenApplePayExtensionProvisioning/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"WatchAvailability"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"WatchAvailability"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"WatchAvailability"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/init","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/session(_:activationDidCompleteWith:error:)","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/sessionDidBecomeInactive(_:)","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/sessionDidDeactivate(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/objc(pl)WCSessionDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatchAvailability"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability~1sessionDidBecomeInactive(_:)\/title","value":"sessionDidBecomeInactive:"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability~1sessionDidBecomeInactive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionDidBecomeInactive:"}]},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability\/title","value":"WatchAvailability"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability\/fragments","value":[{"kind":"identifier","text":"WatchAvailability"}]},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability~1sessionDidDeactivate(_:)\/title","value":"sessionDidDeactivate:"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability~1sessionDidDeactivate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionDidDeactivate:"}]},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability~1session(_:activationDidCompleteWith:error:)\/title","value":"session:activationDidCompleteWithState:error:"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability~1session(_:activationDidCompleteWith:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"session:activationDidCompleteWithState:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}