{"metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"IsWatchActivated","kind":"identifier"}],"title":"WatchAvailability.IsWatchActivated","role":"symbol","externalID":"s:25AdyenApplePayProvisioning17WatchAvailabilityC02IsE9Activateda","navigatorTitle":[{"text":"IsWatchActivated","kind":"identifier"}],"symbolKind":"typealias","modules":[{"name":"AdyenApplePayProvisioning"}],"roleHeading":"Type Alias"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsWatchActivated","kind":"identifier"},{"text":" = ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/adyenapplepayprovisioning\/watchavailability\/iswatchactivated"]}],"identifier":{"url":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/IsWatchActivated","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Represents a state where a watch session is activated and the watch is paired"}],"hierarchy":{"paths":[["doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability"]]},"references":{"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"WatchAvailability"}],"title":"WatchAvailability","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WatchAvailability"}],"abstract":[{"type":"codeVoice","code":"WatchAvailability"},{"type":"text","text":" class provides functionality to check the availability of the Apple Watch."},{"text":" ","type":"text"},{"text":"The state is retrieved from ","type":"text"},{"type":"codeVoice","code":"WCSession.default"},{"type":"text","text":", which is a global state, be cautious if your app is already using "},{"code":"WCSession","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"as this class reassigns "},{"type":"codeVoice","code":"WCSession.default.delegate"},{"type":"text","text":" property."},{"type":"text","text":" "},{"type":"text","text":"Avoid creating multiple instances of "},{"code":"WatchAvailability","type":"codeVoice"},{"text":"or calling ","type":"text"},{"code":"activate()","type":"codeVoice"},{"text":" method several times in a row.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability","type":"topic","url":"\/documentation\/adyenapplepayprovisioning\/watchavailability"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning":{"kind":"symbol","url":"\/documentation\/adyenapplepayprovisioning","type":"topic","abstract":[],"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","title":"AdyenApplePayProvisioning","role":"collection"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/IsWatchActivated":{"role":"symbol","kind":"symbol","title":"WatchAvailability.IsWatchActivated","navigatorTitle":[{"text":"IsWatchActivated","kind":"identifier"}],"url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/iswatchactivated","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IsWatchActivated"}],"abstract":[{"text":"Represents a state where a watch session is activated and the watch is paired","type":"text"}],"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/IsWatchActivated"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/title","value":"WatchAvailability"},{"value":[{"kind":"identifier","text":"WatchAvailability"}],"path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/fragments","op":"replace"},{"value":[{"text":"WatchAvailability","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}