{"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning"]]},"variants":[{"paths":["\/documentation\/adyenapplepayprovisioning\/adyenapplepayextensionprovisioningtestsversionstring"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/adyenapplepayprovisioning\/adyenapplepayextensionprovisioningtestsversionstring"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AdyenApplePayExtensionProvisioningTestsVersionString","interfaceLanguage":"swift"},"metadata":{"symbolKind":"var","externalID":"c:@AdyenApplePayExtensionProvisioningTestsVersionString","navigatorTitle":[{"text":"AdyenApplePayExtensionProvisioningTestsVersionString","kind":"identifier"}],"roleHeading":"Global Variable","role":"symbol","title":"AdyenApplePayExtensionProvisioningTestsVersionString","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"AdyenApplePayExtensionProvisioningTestsVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"modules":[{"name":"AdyenApplePayProvisioning"}]},"abstract":[{"text":"Project version string for AdyenApplePayExtensionProvisioningTests.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdyenApplePayExtensionProvisioningTestsVersionString"},{"text":": <<error type>>","kind":"text"}]}]}],"references":{"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/AdyenApplePayExtensionProvisioningTestsVersionString":{"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AdyenApplePayExtensionProvisioningTestsVersionString","abstract":[{"text":"Project version string for AdyenApplePayExtensionProvisioningTests.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/adyenapplepayprovisioning\/adyenapplepayextensionprovisioningtestsversionstring","navigatorTitle":[{"kind":"identifier","text":"AdyenApplePayExtensionProvisioningTestsVersionString"}],"title":"AdyenApplePayExtensionProvisioningTestsVersionString","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdyenApplePayExtensionProvisioningTestsVersionString"},{"kind":"text","text":": <<error type>>"}]},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning":{"url":"\/documentation\/adyenapplepayprovisioning","title":"AdyenApplePayProvisioning","role":"collection","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"value":"AdyenApplePayExtensionProvisioningTestsVersionString","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"value":[{"text":"AdyenApplePayExtensionProvisioningTestsVersionString","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:c","text":"unsigned char"},{"kind":"text","text":" "},{"text":"AdyenApplePayExtensionProvisioningTestsVersionString","kind":"identifier"},{"kind":"text","text":"[];"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1AdyenApplePayExtensionProvisioningTestsVersionString\/title","value":"AdyenApplePayExtensionProvisioningTestsVersionString"},{"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1AdyenApplePayExtensionProvisioningTestsVersionString\/fragments","value":[{"text":"AdyenApplePayExtensionProvisioningTestsVersionString","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}