{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/adyenapplepayprovisioning\/watchavailability\/session(_:activationdidcompletewith:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/adyenapplepayprovisioning\/watchavailability\/session(_:activationdidcompletewith:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"session(_:activationDidCompleteWith:error:)","role":"symbol","modules":[{"name":"AdyenApplePayProvisioning"}],"externalID":"c:@M@AdyenApplePayProvisioning@objc(cs)WatchAvailability(im)session:activationDidCompleteWithState:error:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"session"},{"text":"(","kind":"text"},{"text":"WCSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WCSession"},{"kind":"text","text":", "},{"text":"activationDidCompleteWith","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@WCSessionActivationState","text":"WCSessionActivationState"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"text":"session:activationDidCompleteWithState:error:","kind":"identifier"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"WCSessionDelegate.session(_:activationDidCompleteWith:error:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"session","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WCSession","text":"WCSession","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"activationDidCompleteWith","kind":"externalParam"},{"kind":"text","text":" "},{"text":"activationState","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"WCSessionActivationState","preciseIdentifier":"c:@E@WCSessionActivationState"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": ("},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/session(_:activationDidCompleteWith:error:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability"]]},"references":{"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/session(_:activationDidCompleteWith:error:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WCSession","kind":"typeIdentifier","text":"WCSession"},{"kind":"text","text":", "},{"text":"activationDidCompleteWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WCSessionActivationState","preciseIdentifier":"c:@E@WCSessionActivationState","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": ("},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/session(_:activationDidCompleteWith:error:)","title":"session(_:activationDidCompleteWith:error:)","abstract":[],"url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/session(_:activationdidcompletewith:error:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"session:activationDidCompleteWithState:error:","kind":"identifier"}]},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatchAvailability"}],"type":"topic","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability","abstract":[{"type":"codeVoice","code":"WatchAvailability"},{"type":"text","text":" class provides functionality to pair the device with an Apple Watch and check its availability."},{"type":"text","text":" "},{"text":"The state is retrieved from ","type":"text"},{"code":"WCSession.default","type":"codeVoice"},{"type":"text","text":", which is a global state, be cautious if your app is already using "},{"type":"codeVoice","code":"WCSession"},{"text":" ","type":"text"},{"text":"as this class reassigns ","type":"text"},{"code":"WCSession.default.delegate","type":"codeVoice"},{"type":"text","text":" property."},{"text":" ","type":"text"},{"text":"Do not create multiple instances of ","type":"text"},{"type":"codeVoice","code":"WatchAvailability"},{"text":" in case you need to pass the pairing state to multiple ","type":"text"},{"type":"codeVoice","code":"ProvisioningService"},{"type":"text","text":" instances."}],"url":"\/documentation\/adyenapplepayprovisioning\/watchavailability","kind":"symbol","navigatorTitle":[{"text":"WatchAvailability","kind":"identifier"}],"title":"WatchAvailability","role":"symbol"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning":{"title":"AdyenApplePayProvisioning","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","url":"\/documentation\/adyenapplepayprovisioning","kind":"symbol","abstract":[],"role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"session:activationDidCompleteWithState:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"session:activationDidCompleteWithState:error:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"session:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WCSession","text":"WCSession","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activationDidCompleteWithState:"},{"text":"(","kind":"text"},{"text":"WCSessionActivationState","kind":"typeIdentifier","preciseIdentifier":"c:@E@WCSessionActivationState"},{"kind":"text","text":") "},{"text":"activationState","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability~1session(_:activationDidCompleteWith:error:)\/title","value":"session:activationDidCompleteWithState:error:","op":"replace"},{"path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability~1session(_:activationDidCompleteWith:error:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"session:activationDidCompleteWithState:error:","kind":"identifier"}]},{"op":"replace","value":"WatchAvailability","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/title"},{"path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/fragments","op":"replace","value":[{"kind":"identifier","text":"WatchAvailability"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}