//
//  ProvisioningDataRequest.swift
//  Adyen Apple Pay Provisioning
//
//  Copyright (c) 2026 Adyen N.V.
//

import Foundation

/// A request model containing the data required for card provisioning POST endpoint
internal struct ProvisioningDataRequest: Encodable {

    /// The data blob generated by the Apple Pay SDK to be sent to the Adyen server.
    let sdkOutput: Data
}
