{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activate","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"IsWatchActivated","preciseIdentifier":"s:25AdyenApplePayProvisioning17WatchAvailabilityC02IsE9Activateda","kind":"typeIdentifier","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/IsWatchActivated"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"aside","name":"Note","content":[{"inlineContent":[{"text":"This is the preferred method for activation.","type":"text"}],"type":"paragraph"}],"style":"note"},{"type":"aside","name":"Warning","content":[{"inlineContent":[{"text":"This method is not designed for concurrent execution. If an","type":"text"},{"text":" ","type":"text"},{"text":"activation is already in progress, any simultaneous call returns immediately","type":"text"},{"text":" ","type":"text"},{"text":"with an ","type":"text"},{"inlineContent":[{"type":"text","text":"undeterministic"}],"type":"strong"},{"text":" status rather than awaiting the primary result.","type":"text"}],"type":"paragraph"}],"style":"warning"},{"type":"heading","anchor":"Usage-Example","level":3,"text":"Usage Example:"},{"type":"heading","anchor":"%E2%9D%8C-How-NOT-to-do-Concurrent-calls","level":4,"text":"❌ How NOT to do (Concurrent calls):"},{"type":"codeListing","code":["async let first = WatchAvailability.activate()","async let second = WatchAvailability.activate() \/\/ ⚠️ Undeterministic result"],"syntax":"swift"},{"type":"heading","anchor":"%E2%9C%85-How-to-do-Serial-calls","level":4,"text":"✅ How to do (Serial calls):"},{"type":"codeListing","code":["let isActivated = await WatchAvailability.activate()"],"syntax":"swift"}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/adyenapplepayprovisioning\/watchavailability\/activate()-swift.type.method"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/activate()-swift.type.method"},"metadata":{"modules":[{"name":"AdyenApplePayProvisioning"}],"title":"activate()","roleHeading":"Type Method","symbolKind":"method","role":"symbol","externalID":"s:25AdyenApplePayProvisioning17WatchAvailabilityC8activateSbyYaFZ","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activate"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:25AdyenApplePayProvisioning17WatchAvailabilityC02IsE9Activateda","text":"IsWatchActivated"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability"]]},"abstract":[{"type":"text","text":"Activates the shared session and returns the pairing status."}],"references":{"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning":{"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","url":"\/documentation\/adyenapplepayprovisioning","title":"AdyenApplePayProvisioning","abstract":[],"type":"topic","kind":"symbol","role":"collection"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/IsWatchActivated":{"kind":"symbol","title":"WatchAvailability.IsWatchActivated","type":"topic","url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/iswatchactivated","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/IsWatchActivated","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsWatchActivated","kind":"identifier"}],"abstract":[{"type":"text","text":"Indicates whether a watch session is activated and a watch is currently paired."}],"navigatorTitle":[{"kind":"identifier","text":"IsWatchActivated"}]},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/activate()-swift.type.method":{"kind":"symbol","title":"activate()","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/activate()-swift.type.method","url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/activate()-swift.type.method","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activate"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:25AdyenApplePayProvisioning17WatchAvailabilityC02IsE9Activateda","text":"IsWatchActivated"}],"abstract":[{"type":"text","text":"Activates the shared session and returns the pairing status."}]},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability":{"role":"symbol","url":"\/documentation\/adyenapplepayprovisioning\/watchavailability","abstract":[{"type":"text","text":"Manages and checks the availability of an Apple Watch for provisioning."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatchAvailability"}],"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability","navigatorTitle":[{"kind":"identifier","text":"WatchAvailability"}],"kind":"symbol","type":"topic","title":"WatchAvailability"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/title","value":"WatchAvailability"},{"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/fragments","value":[{"text":"WatchAvailability","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/navigatorTitle","op":"replace","value":[{"text":"WatchAvailability","kind":"identifier"}]}]}]}