{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/adyenapplepayprovisioning\/adyenapplepayextensionprovisioningtestsversionnumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/adyenapplepayprovisioning\/adyenapplepayextensionprovisioningtestsversionnumber"]}],"sections":[],"identifier":{"url":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AdyenApplePayExtensionProvisioningTestsVersionNumber","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdyenApplePayExtensionProvisioningTestsVersionNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdyenApplePayExtensionProvisioningTestsVersionNumber"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"title":"AdyenApplePayExtensionProvisioningTestsVersionNumber","roleHeading":"Global Variable","navigatorTitle":[{"text":"AdyenApplePayExtensionProvisioningTestsVersionNumber","kind":"identifier"}],"symbolKind":"var","modules":[{"name":"AdyenApplePayProvisioning"}],"role":"symbol","externalID":"c:@AdyenApplePayExtensionProvisioningTestsVersionNumber"},"hierarchy":{"paths":[["doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning"]]},"kind":"symbol","abstract":[{"text":"Project version number for AdyenApplePayExtensionProvisioningTests.","type":"text"}],"references":{"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/AdyenApplePayExtensionProvisioningTestsVersionNumber":{"role":"symbol","kind":"symbol","title":"AdyenApplePayExtensionProvisioningTestsVersionNumber","navigatorTitle":[{"kind":"identifier","text":"AdyenApplePayExtensionProvisioningTestsVersionNumber"}],"url":"\/documentation\/adyenapplepayprovisioning\/adyenapplepayextensionprovisioningtestsversionnumber","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"AdyenApplePayExtensionProvisioningTestsVersionNumber","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Project version number for AdyenApplePayExtensionProvisioningTests."}],"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AdyenApplePayExtensionProvisioningTestsVersionNumber"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning":{"kind":"symbol","url":"\/documentation\/adyenapplepayprovisioning","type":"topic","abstract":[],"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","title":"AdyenApplePayProvisioning","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"path":"\/metadata\/title","value":"AdyenApplePayExtensionProvisioningTestsVersionNumber","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AdyenApplePayExtensionProvisioningTestsVersionNumber"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdyenApplePayExtensionProvisioningTestsVersionNumber"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"AdyenApplePayExtensionProvisioningTestsVersionNumber","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1AdyenApplePayExtensionProvisioningTestsVersionNumber\/title"},{"path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1AdyenApplePayExtensionProvisioningTestsVersionNumber\/fragments","value":[{"kind":"identifier","text":"AdyenApplePayExtensionProvisioningTestsVersionNumber"}],"op":"replace"}]}]}