{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability"},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.adyen.AdyenApplePayProvisioning\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.adyen.AdyenApplePayProvisioning\/objc(pl)NSObject","doc:\/\/com.adyen.AdyenApplePayProvisioning\/s7CVarArgP","doc:\/\/com.adyen.AdyenApplePayProvisioning\/s28CustomDebugStringConvertibleP","doc:\/\/com.adyen.AdyenApplePayProvisioning\/s23CustomStringConvertibleP","doc:\/\/com.adyen.AdyenApplePayProvisioning\/SQ","doc:\/\/com.adyen.AdyenApplePayProvisioning\/SH","doc:\/\/com.adyen.AdyenApplePayProvisioning\/objc(pl)WCSessionDelegate"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatchAvailability"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Usage example:"}],"type":"paragraph"},{"code":["let isPaired = await WatchAvailability().pair()","let canAddCard = provisioningService.canAddCard(isWatchPaired: isPaired)"],"type":"codeListing","syntax":null}],"kind":"content"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WatchAvailability","kind":"identifier"}],"modules":[{"name":"AdyenApplePayProvisioning"}],"roleHeading":"Class","symbolKind":"class","externalID":"c:@M@AdyenApplePayProvisioning@objc(cs)WatchAvailability","navigatorTitle":[{"text":"WatchAvailability","kind":"identifier"}],"role":"symbol","title":"WatchAvailability"},"abstract":[{"type":"codeVoice","code":"WatchAvailability"},{"text":" class provides functionality to pair the device with an Apple Watch and check its availability.","type":"text"},{"type":"text","text":" "},{"text":"The state is retrieved from ","type":"text"},{"type":"codeVoice","code":"WCSession.default"},{"type":"text","text":", which is a global state, be cautious if your app is already using "},{"type":"codeVoice","code":"WCSession"},{"text":" ","type":"text"},{"type":"text","text":"as this class reassigns "},{"type":"codeVoice","code":"WCSession.default.delegate"},{"text":" property.","type":"text"},{"text":" ","type":"text"},{"text":"Do not create multiple instances of ","type":"text"},{"type":"codeVoice","code":"WatchAvailability"},{"type":"text","text":" in case you need to pass the pairing state to multiple "},{"type":"codeVoice","code":"ProvisioningService"},{"text":" instances.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/adyenapplepayprovisioning\/watchavailability"]},{"paths":["\/documentation\/adyenapplepayprovisioning\/watchavailability"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning"]]},"topicSections":[{"identifiers":["doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/init()"],"title":"Initializers"},{"title":"Instance Methods","identifiers":["doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/pair()","doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/session(_:activationDidCompleteWith:error:)","doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/sessionDidBecomeInactive(_:)","doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/sessionDidDeactivate(_:)"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/IsWatchPaired"]}],"references":{"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/init()":{"abstract":[],"title":"init()","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/init()","type":"topic","role":"symbol","url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol"},"doc://com.adyen.AdyenApplePayProvisioning/objc(pl)WCSessionDelegate":{"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/objc(pl)WCSessionDelegate","title":"WCSessionDelegate","type":"unresolvable"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/pair()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pair","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:25AdyenApplePayProvisioning17WatchAvailabilityC02IsE6Paireda","kind":"typeIdentifier","text":"IsWatchPaired"}],"abstract":[{"text":"This method is used to pair the device with an Apple Watch and check its availability.","type":"text"}],"kind":"symbol","title":"pair()","type":"topic","url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/pair()","role":"symbol","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/pair()"},"doc://com.adyen.AdyenApplePayProvisioning/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning":{"abstract":[],"title":"AdyenApplePayProvisioning","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","type":"topic","role":"collection","url":"\/documentation\/adyenapplepayprovisioning","kind":"symbol"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/sessionDidDeactivate(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionDidDeactivate","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WCSession","kind":"typeIdentifier","text":"WCSession"},{"text":")","kind":"text"}],"title":"sessionDidDeactivate(_:)","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/sessiondiddeactivate(_:)","role":"symbol","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/sessionDidDeactivate(_:)","navigatorTitle":[{"text":"sessionDidDeactivate:","kind":"identifier"}]},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability":{"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatchAvailability"}],"navigatorTitle":[{"kind":"identifier","text":"WatchAvailability"}],"abstract":[{"code":"WatchAvailability","type":"codeVoice"},{"type":"text","text":" class provides functionality to pair the device with an Apple Watch and check its availability."},{"type":"text","text":" "},{"text":"The state is retrieved from ","type":"text"},{"type":"codeVoice","code":"WCSession.default"},{"text":", which is a global state, be cautious if your app is already using ","type":"text"},{"code":"WCSession","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"as this class reassigns "},{"type":"codeVoice","code":"WCSession.default.delegate"},{"type":"text","text":" property."},{"text":" ","type":"text"},{"type":"text","text":"Do not create multiple instances of "},{"type":"codeVoice","code":"WatchAvailability"},{"type":"text","text":" in case you need to pass the pairing state to multiple "},{"type":"codeVoice","code":"ProvisioningService"},{"type":"text","text":" instances."}],"title":"WatchAvailability","kind":"symbol","url":"\/documentation\/adyenapplepayprovisioning\/watchavailability"},"doc://com.adyen.AdyenApplePayProvisioning/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.adyen.AdyenApplePayProvisioning/SH":{"type":"unresolvable","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/SH","title":"Swift.Hashable"},"doc://com.adyen.AdyenApplePayProvisioning/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.adyen.AdyenApplePayProvisioning/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/SQ","title":"Swift.Equatable"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/IsWatchPaired":{"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"IsWatchPaired"}],"type":"topic","abstract":[],"url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/iswatchpaired","title":"WatchAvailability.IsWatchPaired","role":"symbol","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/IsWatchPaired","navigatorTitle":[{"text":"IsWatchPaired","kind":"identifier"}]},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/session(_:activationDidCompleteWith:error:)":{"role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WCSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WCSession"},{"kind":"text","text":", "},{"text":"activationDidCompleteWith","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WCSessionActivationState","preciseIdentifier":"c:@E@WCSessionActivationState"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"title":"session(_:activationDidCompleteWith:error:)","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/session(_:activationDidCompleteWith:error:)","navigatorTitle":[{"text":"session:activationDidCompleteWithState:error:","kind":"identifier"}],"type":"topic","url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/session(_:activationdidcompletewith:error:)"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/sessionDidBecomeInactive(_:)":{"abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sessionDidBecomeInactive"},{"text":"(","kind":"text"},{"text":"WCSession","preciseIdentifier":"c:objc(cs)WCSession","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/sessiondidbecomeinactive(_:)","type":"topic","navigatorTitle":[{"text":"sessionDidBecomeInactive:","kind":"identifier"}],"kind":"symbol","title":"sessionDidBecomeInactive(_:)","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/sessionDidBecomeInactive(_:)"},"doc://com.adyen.AdyenApplePayProvisioning/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.adyen.AdyenApplePayProvisioning/objc(cs)NSObject":{"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"WatchAvailability","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"WatchAvailability","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"WatchAvailability"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/init()","doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/session(_:activationDidCompleteWith:error:)","doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/sessionDidBecomeInactive(_:)","doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/sessionDidDeactivate(_:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.adyen.AdyenApplePayProvisioning\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.adyen.AdyenApplePayProvisioning\/objc(pl)WCSessionDelegate"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WatchAvailability","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability~1init()\/title","value":"init"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability~1init()\/fragments"},{"value":"sessionDidDeactivate:","op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability~1sessionDidDeactivate(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability~1sessionDidDeactivate(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sessionDidDeactivate:"}]},{"op":"replace","value":"WatchAvailability","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/fragments","value":[{"kind":"identifier","text":"WatchAvailability"}]},{"value":"session:activationDidCompleteWithState:error:","op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability~1session(_:activationDidCompleteWith:error:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability~1session(_:activationDidCompleteWith:error:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"session:activationDidCompleteWithState:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability~1sessionDidBecomeInactive(_:)\/title","value":"sessionDidBecomeInactive:","op":"replace"},{"path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability~1sessionDidBecomeInactive(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sessionDidBecomeInactive:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}