{"kind":"symbol","sections":[],"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/ExtensionProvisioningService"]},{"title":"Protocols","identifiers":["doc:\/\/com.adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/ExtensionProvisioningServiceDelegate"]},{"identifiers":["doc:\/\/com.adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/ExtensionProvisioningServiceError"],"title":"Enumerations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/adyenapplepayextensionprovisioning"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/adyenapplepayextensionprovisioning"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[[]]},"metadata":{"role":"collection","modules":[{"name":"AdyenApplePayExtensionProvisioning"}],"externalID":"AdyenApplePayExtensionProvisioning","roleHeading":"Framework","title":"AdyenApplePayExtensionProvisioning","symbolKind":"module"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning"},"references":{"doc://com.adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/AdyenApplePayExtensionProvisioningVersionNumber":{"role":"symbol","title":"AdyenApplePayExtensionProvisioningVersionNumber","type":"topic","url":"\/documentation\/adyenapplepayextensionprovisioning\/adyenapplepayextensionprovisioningversionnumber","fragments":[{"text":"AdyenApplePayExtensionProvisioningVersionNumber","kind":"identifier"}],"abstract":[{"type":"text","text":"Project version number for AdyenApplePayExtensionProvisioning."}],"identifier":"doc:\/\/com.adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/AdyenApplePayExtensionProvisioningVersionNumber","kind":"symbol"},"doc://com.adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/AdyenApplePayExtensionProvisioningVersionString":{"url":"\/documentation\/adyenapplepayextensionprovisioning\/adyenapplepayextensionprovisioningversionstring","role":"symbol","kind":"symbol","title":"AdyenApplePayExtensionProvisioningVersionString","identifier":"doc:\/\/com.adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/AdyenApplePayExtensionProvisioningVersionString","abstract":[{"type":"text","text":"Project version string for AdyenApplePayExtensionProvisioning."}],"fragments":[{"text":"AdyenApplePayExtensionProvisioningVersionString","kind":"identifier"}],"type":"topic"},"doc://com.adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning":{"title":"AdyenApplePayExtensionProvisioning","kind":"symbol","identifier":"doc:\/\/com.adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning","role":"collection","type":"topic","url":"\/documentation\/adyenapplepayextensionprovisioning","abstract":[]},"doc://com.adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/ExtensionProvisioningServiceError":{"type":"topic","identifier":"doc:\/\/com.adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/ExtensionProvisioningServiceError","title":"ExtensionProvisioningServiceError","kind":"symbol","url":"\/documentation\/adyenapplepayextensionprovisioning\/extensionprovisioningserviceerror","abstract":[{"text":"Errors thrown by ","type":"text"},{"code":"ExtensionProvisioningService","type":"codeVoice"}],"navigatorTitle":[{"text":"ExtensionProvisioningServiceError","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExtensionProvisioningServiceError"}]},"doc://com.adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/ExtensionProvisioningServiceDelegate":{"type":"topic","title":"ExtensionProvisioningServiceDelegate","role":"symbol","navigatorTitle":[{"text":"ExtensionProvisioningServiceDelegate","kind":"identifier"}],"abstract":[{"text":"The protocol implemented to fullfill the provision request while adding a card to Apple Pay.","type":"text"}],"identifier":"doc:\/\/com.adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/ExtensionProvisioningServiceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExtensionProvisioningServiceDelegate"}],"kind":"symbol","url":"\/documentation\/adyenapplepayextensionprovisioning\/extensionprovisioningservicedelegate"},"doc://com.adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/ExtensionProvisioningService":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/ExtensionProvisioningService","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ExtensionProvisioningService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ExtensionProvisioningService"}],"title":"ExtensionProvisioningService","url":"\/documentation\/adyenapplepayextensionprovisioning\/extensionprovisioningservice","abstract":[{"type":"text","text":"Service that supports an Issuer Provisioning Extension."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"title":"Variables","identifiers":["doc:\/\/com.adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/AdyenApplePayExtensionProvisioningVersionNumber","doc:\/\/com.adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/AdyenApplePayExtensionProvisioningVersionString"]}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"}]}]}