{"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"AdyenApplePayProvisioning"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activate"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"IsWatchActivated","preciseIdentifier":"s:25AdyenApplePayProvisioning17WatchAvailabilityC02IsE9Activateda"}],"roleHeading":"Instance Method","title":"activate()","symbolKind":"method","externalID":"s:25AdyenApplePayProvisioning17WatchAvailabilityC8activateSbyYaF","role":"symbol","platforms":[{"deprecated":true,"message":"Use the static activate() method to avoid overriding the global WCSession.default delegate in multiple instances.","beta":false,"unavailable":false}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activate","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"IsWatchActivated","kind":"typeIdentifier","preciseIdentifier":"s:25AdyenApplePayProvisioning17WatchAvailabilityC02IsE9Activateda","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/IsWatchActivated"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Avoid concurrent calls. Subsequent callers will not wait for","type":"text"},{"text":" ","type":"text"},{"text":"the existing activation to finish, leading to an ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"undeterministic"}]},{"text":" \/\/\/ return value based on the session’s transient state.","type":"text"}]}],"style":"warning","name":"Warning","type":"aside"},{"type":"heading","text":"Usage Example:","anchor":"Usage-Example","level":3},{"text":"❌ How NOT to do (Concurrent calls):","anchor":"%E2%9D%8C-How-NOT-to-do-Concurrent-calls","type":"heading","level":4},{"type":"codeListing","syntax":"swift","code":["let availability = WatchAvailability()","async let first = availability.activate()","async let second = availability.activate() \/\/ ⚠️ Undeterministic result"]},{"text":"✅ How to do (Serial calls):","type":"heading","level":4,"anchor":"%E2%9C%85-How-to-do-Serial-calls"},{"syntax":"swift","code":["let availability = WatchAvailability()","let isActivated = await availability.activate()"],"type":"codeListing"}]}],"variants":[{"paths":["\/documentation\/adyenapplepayprovisioning\/watchavailability\/activate()-swift.method"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Activates the session and returns whether a watch is paired and activated."}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use the static activate() method to avoid overriding the global WCSession.default delegate in multiple instances."}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability"]]},"identifier":{"url":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/activate()-swift.method","interfaceLanguage":"swift"},"references":{"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning":{"role":"collection","abstract":[],"title":"AdyenApplePayProvisioning","kind":"symbol","type":"topic","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","url":"\/documentation\/adyenapplepayprovisioning"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/activate()-swift.method":{"type":"topic","abstract":[{"text":"Activates the session and returns whether a watch is paired and activated.","type":"text"}],"kind":"symbol","role":"symbol","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activate"},{"kind":"text","text":"() "},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"IsWatchActivated","preciseIdentifier":"s:25AdyenApplePayProvisioning17WatchAvailabilityC02IsE9Activateda","kind":"typeIdentifier"}],"url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/activate()-swift.method","title":"activate()","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/activate()-swift.method"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability":{"type":"topic","abstract":[{"type":"text","text":"Manages and checks the availability of an Apple Watch for provisioning."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WatchAvailability"}],"url":"\/documentation\/adyenapplepayprovisioning\/watchavailability","navigatorTitle":[{"kind":"identifier","text":"WatchAvailability"}],"title":"WatchAvailability","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/IsWatchActivated":{"type":"topic","abstract":[{"text":"Indicates whether a watch session is activated and a watch is currently paired.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IsWatchActivated"}],"url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/iswatchactivated","navigatorTitle":[{"kind":"identifier","text":"IsWatchActivated"}],"title":"WatchAvailability.IsWatchActivated","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/IsWatchActivated"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/title","value":"WatchAvailability"},{"path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/fragments","value":[{"text":"WatchAvailability","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/navigatorTitle","value":[{"kind":"identifier","text":"WatchAvailability"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}