{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPaymentPassViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKAddPaymentPassViewController","preciseIdentifier":"c:objc(cs)PKAddPaymentPassViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishAdding"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPaymentPass","preciseIdentifier":"c:objc(cs)PKPaymentPass"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/adyenapplepayextensionprovisioning\/pkaddpassviewcontrolling\/addpaymentpassviewcontroller(_:didfinishadding:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/adyenapplepayextensionprovisioning\/pkaddpassviewcontrolling\/addpaymentpassviewcontroller(_:didfinishadding:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/PKAddPassViewControlling\/addPaymentPassViewController(_:didFinishAdding:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PKAddPaymentPassViewControllerDelegate.addPaymentPassViewController(_:didFinishAdding:error:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPaymentPassViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKAddPaymentPassViewController","preciseIdentifier":"c:objc(cs)PKAddPaymentPassViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishAdding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPaymentPass","preciseIdentifier":"c:objc(cs)PKPaymentPass"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"title":"addPaymentPassViewController(_:didFinishAdding:error:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@AdyenApplePayExtensionProvisioning@objc(cs)PKAddPassViewControlling(im)addPaymentPassViewController:didFinishAddingPaymentPass:error:","modules":[{"name":"AdyenApplePayExtensionProvisioning"}],"navigatorTitle":[{"kind":"identifier","text":"addPaymentPassViewController:didFinishAddingPaymentPass:error:"}]},"hierarchy":{"paths":[["doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/PKAddPassViewControlling"]]},"references":{"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning":{"role":"collection","title":"AdyenApplePayExtensionProvisioning","abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning","kind":"symbol","type":"topic","url":"\/documentation\/adyenapplepayextensionprovisioning"},"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/PKAddPassViewControlling/addPaymentPassViewController(_:didFinishAdding:error:)":{"role":"symbol","title":"addPaymentPassViewController(_:didFinishAdding:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPaymentPassViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKAddPaymentPassViewController","preciseIdentifier":"c:objc(cs)PKAddPaymentPassViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishAdding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPaymentPass","preciseIdentifier":"c:objc(cs)PKPaymentPass"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/PKAddPassViewControlling\/addPaymentPassViewController(_:didFinishAdding:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addPaymentPassViewController:didFinishAddingPaymentPass:error:"}],"url":"\/documentation\/adyenapplepayextensionprovisioning\/pkaddpassviewcontrolling\/addpaymentpassviewcontroller(_:didfinishadding:error:)"},"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/PKAddPassViewControlling":{"role":"symbol","title":"PKAddPassViewControlling","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKAddPassViewControlling"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/PKAddPassViewControlling","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PKAddPassViewControlling"}],"url":"\/documentation\/adyenapplepayextensionprovisioning\/pkaddpassviewcontrolling"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addPaymentPassViewController:didFinishAddingPaymentPass:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPaymentPassViewController:didFinishAddingPaymentPass:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addPaymentPassViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKAddPaymentPassViewController","preciseIdentifier":"c:objc(cs)PKAddPaymentPassViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishAddingPaymentPass:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPaymentPass","preciseIdentifier":"c:objc(cs)PKPaymentPass"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pass"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1PKAddPassViewControlling~1addPaymentPassViewController(_:didFinishAdding:error:)\/title","value":"addPaymentPassViewController:didFinishAddingPaymentPass:error:"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1PKAddPassViewControlling~1addPaymentPassViewController(_:didFinishAdding:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPaymentPassViewController:didFinishAddingPaymentPass:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1PKAddPassViewControlling\/title","value":"PKAddPassViewControlling"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1PKAddPassViewControlling\/fragments","value":[{"kind":"identifier","text":"PKAddPassViewControlling"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}