{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPaymentPassViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKAddPaymentPassViewController","preciseIdentifier":"c:objc(cs)PKAddPaymentPassViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"generateRequestWithCertificateChain"},{"kind":"text","text":" "},{"kind":"internalParam","text":"certificates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"nonce"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nonceSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"PKAddPaymentPassRequest","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequest"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/adyenapplepayextensionprovisioning\/pkaddpassviewcontrolling\/addpaymentpassviewcontroller(_:generaterequestwithcertificatechain:nonce:noncesignature:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/adyenapplepayextensionprovisioning\/pkaddpassviewcontrolling\/addpaymentpassviewcontroller(_:generaterequestwithcertificatechain:nonce:noncesignature:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/PKAddPassViewControlling\/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PKAddPaymentPassViewControllerDelegate.addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPaymentPassViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKAddPaymentPassViewController","preciseIdentifier":"c:objc(cs)PKAddPaymentPassViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"generateRequestWithCertificateChain"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"nonce"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nonceSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"PKAddPaymentPassRequest","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequest"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@AdyenApplePayExtensionProvisioning@objc(cs)PKAddPassViewControlling(im)addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:","modules":[{"name":"AdyenApplePayExtensionProvisioning"}],"navigatorTitle":[{"kind":"identifier","text":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/PKAddPassViewControlling"]]},"references":{"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning":{"role":"collection","title":"AdyenApplePayExtensionProvisioning","abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning","kind":"symbol","type":"topic","url":"\/documentation\/adyenapplepayextensionprovisioning"},"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/PKAddPassViewControlling/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)":{"role":"symbol","title":"addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPaymentPassViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKAddPaymentPassViewController","preciseIdentifier":"c:objc(cs)PKAddPaymentPassViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"generateRequestWithCertificateChain"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"nonce"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nonceSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"PKAddPaymentPassRequest","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequest"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/PKAddPassViewControlling\/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"}],"url":"\/documentation\/adyenapplepayextensionprovisioning\/pkaddpassviewcontrolling\/addpaymentpassviewcontroller(_:generaterequestwithcertificatechain:nonce:noncesignature:completionhandler:)"},"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/PKAddPassViewControlling":{"role":"symbol","title":"PKAddPassViewControlling","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKAddPassViewControlling"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/PKAddPassViewControlling","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PKAddPassViewControlling"}],"url":"\/documentation\/adyenapplepayextensionprovisioning\/pkaddpassviewcontrolling"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addPaymentPassViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKAddPaymentPassViewController","preciseIdentifier":"c:objc(cs)PKAddPaymentPassViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateRequestWithCertificateChain:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSData *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"certificates"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonce:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nonce"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonceSignature:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nonceSignature"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(PKAddPaymentPassRequest *)","preciseIdentifier":"c:BFv(#*$objc(cs)PKAddPaymentPassRequest)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1PKAddPassViewControlling~1addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)\/title","value":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1PKAddPassViewControlling~1addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1PKAddPassViewControlling\/title","value":"PKAddPassViewControlling"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1PKAddPassViewControlling\/fragments","value":[{"kind":"identifier","text":"PKAddPassViewControlling"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}