{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionDidDeactivate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WCSession","preciseIdentifier":"c:objc(cs)WCSession"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/adyenapplepayextensionprovisioning\/watchavailability\/sessiondiddeactivate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/adyenapplepayextensionprovisioning\/watchavailability\/sessiondiddeactivate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/sessionDidDeactivate(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"WCSessionDelegate.sessionDidDeactivate(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionDidDeactivate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WCSession","preciseIdentifier":"c:objc(cs)WCSession"},{"kind":"text","text":")"}],"title":"sessionDidDeactivate(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@AdyenApplePayExtensionProvisioning@objc(cs)WatchAvailability(im)sessionDidDeactivate:","modules":[{"name":"AdyenApplePayExtensionProvisioning"}],"navigatorTitle":[{"kind":"identifier","text":"sessionDidDeactivate:"}]},"hierarchy":{"paths":[["doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability"]]},"references":{"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/WatchAvailability/sessionDidDeactivate(_:)":{"role":"symbol","title":"sessionDidDeactivate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionDidDeactivate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WCSession","preciseIdentifier":"c:objc(cs)WCSession"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/sessionDidDeactivate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionDidDeactivate:"}],"url":"\/documentation\/adyenapplepayextensionprovisioning\/watchavailability\/sessiondiddeactivate(_:)"},"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/WatchAvailability":{"role":"symbol","title":"WatchAvailability","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatchAvailability"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WatchAvailability"}],"url":"\/documentation\/adyenapplepayextensionprovisioning\/watchavailability"},"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning":{"role":"collection","title":"AdyenApplePayExtensionProvisioning","abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning","kind":"symbol","type":"topic","url":"\/documentation\/adyenapplepayextensionprovisioning"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sessionDidDeactivate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionDidDeactivate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"sessionDidDeactivate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WCSession","preciseIdentifier":"c:objc(cs)WCSession"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"_"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability~1sessionDidDeactivate(_:)\/title","value":"sessionDidDeactivate:"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability~1sessionDidDeactivate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionDidDeactivate:"}]},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability\/title","value":"WatchAvailability"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability\/fragments","value":[{"kind":"identifier","text":"WatchAvailability"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}