{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WCSession","preciseIdentifier":"c:objc(cs)WCSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activationDidCompleteWith"},{"kind":"text","text":" "},{"kind":"internalParam","text":"activationState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WCSessionActivationState","preciseIdentifier":"c:@E@WCSessionActivationState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/adyenapplepayextensionprovisioning\/watchavailability\/session(_:activationdidcompletewith:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/adyenapplepayextensionprovisioning\/watchavailability\/session(_:activationdidcompletewith:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/session(_:activationDidCompleteWith:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"WCSessionDelegate.session(_:activationDidCompleteWith:error:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WCSession","preciseIdentifier":"c:objc(cs)WCSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activationDidCompleteWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WCSessionActivationState","preciseIdentifier":"c:@E@WCSessionActivationState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"title":"session(_:activationDidCompleteWith:error:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@AdyenApplePayExtensionProvisioning@objc(cs)WatchAvailability(im)session:activationDidCompleteWithState:error:","modules":[{"name":"AdyenApplePayExtensionProvisioning"}],"navigatorTitle":[{"kind":"identifier","text":"session:activationDidCompleteWithState:error:"}]},"hierarchy":{"paths":[["doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning","doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability"]]},"references":{"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning":{"role":"collection","title":"AdyenApplePayExtensionProvisioning","abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning","kind":"symbol","type":"topic","url":"\/documentation\/adyenapplepayextensionprovisioning"},"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/WatchAvailability/session(_:activationDidCompleteWith:error:)":{"role":"symbol","title":"session(_:activationDidCompleteWith:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WCSession","preciseIdentifier":"c:objc(cs)WCSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activationDidCompleteWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WCSessionActivationState","preciseIdentifier":"c:@E@WCSessionActivationState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability\/session(_:activationDidCompleteWith:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"session:activationDidCompleteWithState:error:"}],"url":"\/documentation\/adyenapplepayextensionprovisioning\/watchavailability\/session(_:activationdidcompletewith:error:)"},"doc://adyen.AdyenApplePayExtensionProvisioning/documentation/AdyenApplePayExtensionProvisioning/WatchAvailability":{"role":"symbol","title":"WatchAvailability","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatchAvailability"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayExtensionProvisioning\/documentation\/AdyenApplePayExtensionProvisioning\/WatchAvailability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WatchAvailability"}],"url":"\/documentation\/adyenapplepayextensionprovisioning\/watchavailability"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"session:activationDidCompleteWithState:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"session:activationDidCompleteWithState:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"session:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WCSession","preciseIdentifier":"c:objc(cs)WCSession"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"kind":"identifier","text":"activationDidCompleteWithState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WCSessionActivationState","preciseIdentifier":"c:@E@WCSessionActivationState"},{"kind":"text","text":") "},{"kind":"internalParam","text":"activationState"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability~1session(_:activationDidCompleteWith:error:)\/title","value":"session:activationDidCompleteWithState:error:"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability~1session(_:activationDidCompleteWith:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"session:activationDidCompleteWithState:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability\/title","value":"WatchAvailability"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayExtensionProvisioning~1documentation~1AdyenApplePayExtensionProvisioning~1WatchAvailability\/fragments","value":[{"kind":"identifier","text":"WatchAvailability"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}