{"variants":[{"paths":["\/documentation\/adyenapplepayprovisioning"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/adyenapplepayprovisioning"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/ProvisioningService","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability"]},{"title":"Protocols","identifiers":["doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AddPassViewControlling","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AddPassViewControllingDelegate","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PassLibrary","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PrimaryAccountIdentifiable","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/ProvisioningServiceDelegate","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/RemoteLibraryAvailability"]},{"title":"Structures","identifiers":["doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/CanAddCardDetails","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/SDKActivationDataInput","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/SDKOutput","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/SDKProvisioningInput"]},{"title":"Variables","identifiers":["doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AdyenApplePayExtensionProvisioningTestsVersionNumber","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AdyenApplePayExtensionProvisioningTestsVersionString"]},{"title":"Enumerations","identifiers":["doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/ActivationDataError","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PassLocation","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/ProvisioningServiceError","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/ProvisioningUtils"]},{"title":"Extended Modules","identifiers":["doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PassKit"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"AdyenApplePayProvisioning","title":"AdyenApplePayProvisioning","symbolKind":"module","role":"collection","modules":[{"name":"AdyenApplePayProvisioning"}]},"hierarchy":{"paths":[[]]},"references":{"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/AddPassViewControllingDelegate":{"role":"symbol","title":"AddPassViewControllingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddPassViewControllingDelegate"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AddPassViewControllingDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddPassViewControllingDelegate"}],"url":"\/documentation\/adyenapplepayprovisioning\/addpassviewcontrollingdelegate"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/ProvisioningServiceDelegate":{"role":"symbol","title":"ProvisioningServiceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProvisioningServiceDelegate"}],"abstract":[{"type":"text","text":"The protocol implemented to fullfill the provision request while adding a card to Apple Pay."}],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/ProvisioningServiceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProvisioningServiceDelegate"}],"url":"\/documentation\/adyenapplepayprovisioning\/provisioningservicedelegate"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability":{"role":"symbol","title":"WatchAvailability","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatchAvailability"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WatchAvailability"}],"url":"\/documentation\/adyenapplepayprovisioning\/watchavailability"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/AdyenApplePayExtensionProvisioningTestsVersionNumber":{"role":"symbol","title":"AdyenApplePayExtensionProvisioningTestsVersionNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdyenApplePayExtensionProvisioningTestsVersionNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Project version number for AdyenApplePayExtensionProvisioningTests."}],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AdyenApplePayExtensionProvisioningTestsVersionNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdyenApplePayExtensionProvisioningTestsVersionNumber"}],"url":"\/documentation\/adyenapplepayprovisioning\/adyenapplepayextensionprovisioningtestsversionnumber"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/SDKOutput":{"role":"symbol","title":"SDKOutput","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKOutput"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/SDKOutput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDKOutput"}],"url":"\/documentation\/adyenapplepayprovisioning\/sdkoutput"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/PKAddPassViewControlling":{"role":"symbol","title":"PKAddPassViewControlling","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKAddPassViewControlling"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PKAddPassViewControlling"}],"url":"\/documentation\/adyenapplepayprovisioning\/pkaddpassviewcontrolling"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/ProvisioningUtils":{"role":"symbol","title":"ProvisioningUtils","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProvisioningUtils"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/ProvisioningUtils","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProvisioningUtils"}],"url":"\/documentation\/adyenapplepayprovisioning\/provisioningutils"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/AddPassViewControlling":{"role":"symbol","title":"AddPassViewControlling","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddPassViewControlling"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AddPassViewControlling","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddPassViewControlling"}],"url":"\/documentation\/adyenapplepayprovisioning\/addpassviewcontrolling"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/ActivationDataError":{"role":"symbol","title":"ActivationDataError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivationDataError"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/ActivationDataError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActivationDataError"}],"url":"\/documentation\/adyenapplepayprovisioning\/activationdataerror"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/SDKProvisioningInput":{"role":"symbol","title":"SDKProvisioningInput","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKProvisioningInput"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/SDKProvisioningInput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDKProvisioningInput"}],"url":"\/documentation\/adyenapplepayprovisioning\/sdkprovisioninginput"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning":{"role":"collection","title":"AdyenApplePayProvisioning","abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","kind":"symbol","type":"topic","url":"\/documentation\/adyenapplepayprovisioning"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/PrimaryAccountIdentifiable":{"role":"symbol","title":"PrimaryAccountIdentifiable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrimaryAccountIdentifiable"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PrimaryAccountIdentifiable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrimaryAccountIdentifiable"}],"url":"\/documentation\/adyenapplepayprovisioning\/primaryaccountidentifiable"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/ProvisioningServiceError":{"role":"symbol","title":"ProvisioningServiceError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProvisioningServiceError"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/ProvisioningServiceError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProvisioningServiceError"}],"url":"\/documentation\/adyenapplepayprovisioning\/provisioningserviceerror"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/RemoteLibraryAvailability":{"role":"symbol","title":"RemoteLibraryAvailability","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteLibraryAvailability"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/RemoteLibraryAvailability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RemoteLibraryAvailability"}],"url":"\/documentation\/adyenapplepayprovisioning\/remotelibraryavailability"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/CanAddCardDetails":{"role":"symbol","title":"CanAddCardDetails","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CanAddCardDetails"}],"abstract":[{"type":"text","text":"Object containing details on where this card can be added."}],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/CanAddCardDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CanAddCardDetails"}],"url":"\/documentation\/adyenapplepayprovisioning\/canaddcarddetails"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/PassKit":{"role":"collection","title":"PassKit","abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PassKit","kind":"symbol","type":"topic","url":"\/documentation\/adyenapplepayprovisioning\/passkit"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/SDKActivationDataInput":{"role":"symbol","title":"SDKActivationDataInput","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKActivationDataInput"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/SDKActivationDataInput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDKActivationDataInput"}],"url":"\/documentation\/adyenapplepayprovisioning\/sdkactivationdatainput"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/AdyenApplePayExtensionProvisioningTestsVersionString":{"role":"symbol","title":"AdyenApplePayExtensionProvisioningTestsVersionString","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdyenApplePayExtensionProvisioningTestsVersionString"},{"kind":"text","text":": <<error type>>"}],"abstract":[{"type":"text","text":"Project version string for AdyenApplePayExtensionProvisioningTests."}],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AdyenApplePayExtensionProvisioningTestsVersionString","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdyenApplePayExtensionProvisioningTestsVersionString"}],"url":"\/documentation\/adyenapplepayprovisioning\/adyenapplepayextensionprovisioningtestsversionstring"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/PassLocation":{"role":"symbol","title":"PassLocation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassLocation"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PassLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PassLocation"}],"url":"\/documentation\/adyenapplepayprovisioning\/passlocation"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/ProvisioningService":{"role":"symbol","title":"ProvisioningService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProvisioningService"}],"abstract":[{"type":"text","text":"Service that supports In-App Provisioning."}],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/ProvisioningService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProvisioningService"}],"url":"\/documentation\/adyenapplepayprovisioning\/provisioningservice"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/PassLibrary":{"role":"symbol","title":"PassLibrary","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassLibrary"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PassLibrary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PassLibrary"}],"url":"\/documentation\/adyenapplepayprovisioning\/passlibrary"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability"]},{"title":"Variables","identifiers":["doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AdyenApplePayExtensionProvisioningTestsVersionNumber","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AdyenApplePayExtensionProvisioningTestsVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/title","value":"WatchAvailability"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/fragments","value":[{"kind":"identifier","text":"WatchAvailability"}]},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1AdyenApplePayExtensionProvisioningTestsVersionNumber\/title","value":"AdyenApplePayExtensionProvisioningTestsVersionNumber"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1AdyenApplePayExtensionProvisioningTestsVersionNumber\/fragments","value":[{"kind":"identifier","text":"AdyenApplePayExtensionProvisioningTestsVersionNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1PKAddPassViewControlling\/title","value":"PKAddPassViewControlling"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1PKAddPassViewControlling\/fragments","value":[{"kind":"identifier","text":"PKAddPassViewControlling"}]},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1AdyenApplePayExtensionProvisioningTestsVersionString\/title","value":"AdyenApplePayExtensionProvisioningTestsVersionString"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1AdyenApplePayExtensionProvisioningTestsVersionString\/fragments","value":[{"kind":"identifier","text":"AdyenApplePayExtensionProvisioningTestsVersionString"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}