{"metadata":{"role":"symbol","title":"activate()","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activate"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"IsWatchSessionActivated","kind":"typeIdentifier","preciseIdentifier":"s:25AdyenApplePayProvisioning17WatchAvailabilityC02IsE16SessionActivateda"}],"modules":[{"name":"AdyenApplePayProvisioning"}],"externalID":"s:25AdyenApplePayProvisioning17WatchAvailabilityC8activateSbyYaF"},"hierarchy":{"paths":[["doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/activate()","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activate"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:25AdyenApplePayProvisioning17WatchAvailabilityC02IsE16SessionActivateda","kind":"typeIdentifier","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/IsWatchSessionActivated","text":"IsWatchSessionActivated"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Returns A boolean value indicating whether the watch is paired and has been activated.","type":"text"}],"type":"paragraph"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/adyenapplepayprovisioning\/watchavailability\/activate()"]}],"sections":[],"abstract":[{"type":"text","text":"This method is used to check the availability of the Apple Watch and activate it."}],"references":{"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/activate()":{"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/activate()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"activate","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"IsWatchSessionActivated","kind":"typeIdentifier","preciseIdentifier":"s:25AdyenApplePayProvisioning17WatchAvailabilityC02IsE16SessionActivateda"}],"title":"activate()","url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/activate()","type":"topic","abstract":[{"type":"text","text":"This method is used to check the availability of the Apple Watch and activate it."}],"role":"symbol","kind":"symbol"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability":{"url":"\/documentation\/adyenapplepayprovisioning\/watchavailability","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatchAvailability"}],"type":"topic","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability","abstract":[{"type":"codeVoice","code":"WatchAvailability"},{"type":"text","text":" class provides functionality to check the availability of the Apple Watch and activate it."},{"text":" ","type":"text"},{"text":"The state is retrieved from ","type":"text"},{"code":"WCSession.default","type":"codeVoice"},{"type":"text","text":", which is a global state, be cautious if your app is already using "},{"code":"WCSession","type":"codeVoice"},{"text":" ","type":"text"},{"text":"as this class reassigns ","type":"text"},{"code":"WCSession.default.delegate","type":"codeVoice"},{"type":"text","text":" property."},{"type":"text","text":" "},{"text":"Avoid creating multiple instances of ","type":"text"},{"code":"WatchAvailability","type":"codeVoice"},{"type":"text","text":"or calling "},{"type":"codeVoice","code":"activate()"},{"type":"text","text":" method several times in a row."}],"role":"symbol","title":"WatchAvailability","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"WatchAvailability"}]},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning":{"abstract":[],"title":"AdyenApplePayProvisioning","role":"collection","type":"topic","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","url":"\/documentation\/adyenapplepayprovisioning","kind":"symbol"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/IsWatchSessionActivated":{"navigatorTitle":[{"kind":"identifier","text":"IsWatchSessionActivated"}],"kind":"symbol","url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/iswatchsessionactivated","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/IsWatchSessionActivated","abstract":[],"role":"symbol","title":"WatchAvailability.IsWatchSessionActivated","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsWatchSessionActivated","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/title","value":"WatchAvailability"},{"value":[{"kind":"identifier","text":"WatchAvailability"}],"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/navigatorTitle","value":[{"text":"WatchAvailability","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}