{"metadata":{"roleHeading":"Instance Method","role":"symbol","platforms":[{"beta":false,"deprecated":true,"message":"Use `activate` method instead.","unavailable":false,"renamed":"activate"}],"title":"pair()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pair","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:25AdyenApplePayProvisioning17WatchAvailabilityC02IsE9Activateda","text":"IsWatchActivated","kind":"typeIdentifier"}],"modules":[{"name":"AdyenApplePayProvisioning"}],"symbolKind":"method","externalID":"s:25AdyenApplePayProvisioning17WatchAvailabilityC4pairSbyYaF"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/pair()"},"abstract":[{"text":"This method is used to check the availability of the Apple Watch and activate it.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/adyenapplepayprovisioning\/watchavailability\/pair()"]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pair"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/IsWatchActivated","preciseIdentifier":"s:25AdyenApplePayProvisioning17WatchAvailabilityC02IsE9Activateda","kind":"typeIdentifier","text":"IsWatchActivated"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns A boolean value indicating whether the watch is paired and has been activated."}]}]}]}],"kind":"content"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use `activate` method instead."}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability"]]},"references":{"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/IsWatchActivated":{"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/IsWatchActivated","role":"symbol","navigatorTitle":[{"text":"IsWatchActivated","kind":"identifier"}],"type":"topic","title":"WatchAvailability.IsWatchActivated","abstract":[{"text":"Represents a state where a watch session is activated and the watch is paired","type":"text"}],"kind":"symbol","url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/iswatchactivated","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"IsWatchActivated","kind":"identifier"}]},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WatchAvailability","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability","navigatorTitle":[{"kind":"identifier","text":"WatchAvailability"}],"url":"\/documentation\/adyenapplepayprovisioning\/watchavailability","kind":"symbol","abstract":[{"code":"WatchAvailability","type":"codeVoice"},{"type":"text","text":" class provides functionality to check the availability of the Apple Watch."},{"type":"text","text":" "},{"text":"The state is retrieved from ","type":"text"},{"type":"codeVoice","code":"WCSession.default"},{"type":"text","text":", which is a global state, be cautious if your app is already using "},{"type":"codeVoice","code":"WCSession"},{"text":" ","type":"text"},{"text":"as this class reassigns ","type":"text"},{"type":"codeVoice","code":"WCSession.default.delegate"},{"type":"text","text":" property."},{"text":" ","type":"text"},{"text":"Avoid creating multiple instances of ","type":"text"},{"type":"codeVoice","code":"WatchAvailability"},{"type":"text","text":"or calling "},{"code":"activate()","type":"codeVoice"},{"type":"text","text":" method several times in a row."}],"title":"WatchAvailability","role":"symbol"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning":{"abstract":[],"title":"AdyenApplePayProvisioning","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","kind":"symbol","url":"\/documentation\/adyenapplepayprovisioning","type":"topic","role":"collection"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/pair()":{"type":"topic","kind":"symbol","title":"pair()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pair","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:25AdyenApplePayProvisioning17WatchAvailabilityC02IsE9Activateda","kind":"typeIdentifier","text":"IsWatchActivated"}],"role":"symbol","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/pair()","url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/pair()","abstract":[{"text":"This method is used to check the availability of the Apple Watch and activate it.","type":"text"}],"deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/title","value":"WatchAvailability","op":"replace"},{"value":[{"text":"WatchAvailability","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/navigatorTitle","value":[{"text":"WatchAvailability","kind":"identifier"}]}]}]}