{"variants":[{"paths":["\/documentation\/adyenapplepayprovisioning\/watchavailability\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/adyenapplepayprovisioning\/watchavailability\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/init()","interfaceLanguage":"swift"},"metadata":{"symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"AdyenApplePayProvisioning"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","externalID":"c:@M@AdyenApplePayProvisioning@objc(cs)WatchAvailability(im)init","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability":{"url":"\/documentation\/adyenapplepayprovisioning\/watchavailability","navigatorTitle":[{"text":"WatchAvailability","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"WatchAvailability"},{"type":"text","text":" class provides functionality to check the availability of the Apple Watch."},{"type":"text","text":" "},{"type":"text","text":"The state is retrieved from "},{"type":"codeVoice","code":"WCSession.default"},{"type":"text","text":", which is a global state, be cautious if your app is already using "},{"type":"codeVoice","code":"WCSession"},{"text":" ","type":"text"},{"text":"as this class reassigns ","type":"text"},{"type":"codeVoice","code":"WCSession.default.delegate"},{"text":" property.","type":"text"},{"text":" ","type":"text"},{"text":"Avoid creating multiple instances of ","type":"text"},{"code":"WatchAvailability","type":"codeVoice"},{"type":"text","text":"or calling "},{"code":"activate()","type":"codeVoice"},{"text":" method several times in a row.","type":"text"}],"role":"symbol","title":"WatchAvailability","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WatchAvailability","kind":"identifier"}],"identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/WatchAvailability/init()":{"abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/adyenapplepayprovisioning\/watchavailability\/init()","title":"init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/WatchAvailability\/init()","type":"topic","kind":"symbol"},"doc://com.adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning":{"url":"\/documentation\/adyenapplepayprovisioning","identifier":"doc:\/\/com.adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","role":"collection","type":"topic","abstract":[],"title":"AdyenApplePayProvisioning","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"init"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"WatchAvailability","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/title"},{"path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/fragments","op":"replace","value":[{"text":"WatchAvailability","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability\/navigatorTitle","value":[{"kind":"identifier","text":"WatchAvailability"}]},{"path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability~1init()\/title","op":"replace","value":"init"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace","path":"\/references\/doc:~1~1com.adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1WatchAvailability~1init()\/fragments"}]}]}