{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKAddPassViewControlling"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/adyenapplepayprovisioning\/pkaddpassviewcontrolling"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/adyenapplepayprovisioning\/pkaddpassviewcontrolling"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/adyen.AdyenApplePayProvisioning\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AddPassViewControlling","doc:\/\/adyen.AdyenApplePayProvisioning\/objc(pl)NSObject","doc:\/\/adyen.AdyenApplePayProvisioning\/objc(pl)PKAddPaymentPassViewControllerDelegate","doc:\/\/adyen.AdyenApplePayProvisioning\/s7CVarArgP","doc:\/\/adyen.AdyenApplePayProvisioning\/s28CustomDebugStringConvertibleP","doc:\/\/adyen.AdyenApplePayProvisioning\/s23CustomStringConvertibleP","doc:\/\/adyen.AdyenApplePayProvisioning\/SQ","doc:\/\/adyen.AdyenApplePayProvisioning\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling\/addPaymentPassViewController(_:didFinishAdding:error:)","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling\/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling\/create(requestConfiguration:delegate:)","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling\/present(addPassViewController:on:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKAddPassViewControlling"}],"title":"PKAddPassViewControlling","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@AdyenApplePayProvisioning@objc(cs)PKAddPassViewControlling","modules":[{"name":"AdyenApplePayProvisioning"}],"navigatorTitle":[{"kind":"identifier","text":"PKAddPassViewControlling"}]},"hierarchy":{"paths":[["doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning"]]},"references":{"doc://adyen.AdyenApplePayProvisioning/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/SH"},"doc://adyen.AdyenApplePayProvisioning/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/objc(pl)NSObject"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/PKAddPassViewControlling/create(requestConfiguration:delegate:)":{"role":"symbol","title":"create(requestConfiguration:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKAddPaymentPassRequestConfiguration","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddPassViewControllingDelegate","preciseIdentifier":"s:25AdyenApplePayProvisioning30AddPassViewControllingDelegateP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling\/create(requestConfiguration:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/adyenapplepayprovisioning\/pkaddpassviewcontrolling\/create(requestconfiguration:delegate:)"},"doc://adyen.AdyenApplePayProvisioning/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/s7CVarArgP"},"doc://adyen.AdyenApplePayProvisioning/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/objc(cs)NSObject"},"doc://adyen.AdyenApplePayProvisioning/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/s23CustomStringConvertibleP"},"doc://adyen.AdyenApplePayProvisioning/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/s28CustomDebugStringConvertibleP"},"doc://adyen.AdyenApplePayProvisioning/objc(pl)PKAddPaymentPassViewControllerDelegate":{"type":"unresolvable","title":"PKAddPaymentPassViewControllerDelegate","identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/objc(pl)PKAddPaymentPassViewControllerDelegate"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/PKAddPassViewControlling/addPaymentPassViewController(_:didFinishAdding:error:)":{"role":"symbol","title":"addPaymentPassViewController(_:didFinishAdding:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPaymentPassViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKAddPaymentPassViewController","preciseIdentifier":"c:objc(cs)PKAddPaymentPassViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishAdding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPaymentPass","preciseIdentifier":"c:objc(cs)PKPaymentPass"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling\/addPaymentPassViewController(_:didFinishAdding:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addPaymentPassViewController:didFinishAddingPaymentPass:error:"}],"url":"\/documentation\/adyenapplepayprovisioning\/pkaddpassviewcontrolling\/addpaymentpassviewcontroller(_:didfinishadding:error:)"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/AddPassViewControlling":{"role":"symbol","title":"AddPassViewControlling","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddPassViewControlling"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/AddPassViewControlling","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddPassViewControlling"}],"url":"\/documentation\/adyenapplepayprovisioning\/addpassviewcontrolling"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning":{"role":"collection","title":"AdyenApplePayProvisioning","abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning","kind":"symbol","type":"topic","url":"\/documentation\/adyenapplepayprovisioning"},"doc://adyen.AdyenApplePayProvisioning/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/SQ"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/PKAddPassViewControlling/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)":{"role":"symbol","title":"addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPaymentPassViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKAddPaymentPassViewController","preciseIdentifier":"c:objc(cs)PKAddPaymentPassViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"generateRequestWithCertificateChain"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"nonce"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nonceSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"PKAddPaymentPassRequest","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequest"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling\/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"}],"url":"\/documentation\/adyenapplepayprovisioning\/pkaddpassviewcontrolling\/addpaymentpassviewcontroller(_:generaterequestwithcertificatechain:nonce:noncesignature:completionhandler:)"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/PKAddPassViewControlling":{"role":"symbol","title":"PKAddPassViewControlling","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKAddPassViewControlling"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PKAddPassViewControlling"}],"url":"\/documentation\/adyenapplepayprovisioning\/pkaddpassviewcontrolling"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/PKAddPassViewControlling/present(addPassViewController:on:)":{"role":"symbol","title":"present(addPassViewController:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"addPassViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling\/present(addPassViewController:on:)","kind":"symbol","type":"topic","url":"\/documentation\/adyenapplepayprovisioning\/pkaddpassviewcontrolling\/present(addpassviewcontroller:on:)"},"doc://adyen.AdyenApplePayProvisioning/documentation/AdyenApplePayProvisioning/PKAddPassViewControlling/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/adyenapplepayprovisioning\/pkaddpassviewcontrolling\/init"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PKAddPassViewControlling"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PKAddPassViewControlling"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PKAddPassViewControlling"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling\/addPaymentPassViewController(_:didFinishAdding:error:)","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling\/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)","doc:\/\/adyen.AdyenApplePayProvisioning\/documentation\/AdyenApplePayProvisioning\/PKAddPassViewControlling\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/adyen.AdyenApplePayProvisioning\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/adyen.AdyenApplePayProvisioning\/objc(pl)PKAddPaymentPassViewControllerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKAddPassViewControlling"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1PKAddPassViewControlling~1addPaymentPassViewController(_:didFinishAdding:error:)\/title","value":"addPaymentPassViewController:didFinishAddingPaymentPass:error:"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1PKAddPassViewControlling~1addPaymentPassViewController(_:didFinishAdding:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPaymentPassViewController:didFinishAddingPaymentPass:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1PKAddPassViewControlling~1addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)\/title","value":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1PKAddPassViewControlling~1addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1PKAddPassViewControlling\/title","value":"PKAddPassViewControlling"},{"op":"replace","path":"\/references\/doc:~1~1adyen.AdyenApplePayProvisioning~1documentation~1AdyenApplePayProvisioning~1PKAddPassViewControlling\/fragments","value":[{"kind":"identifier","text":"PKAddPassViewControlling"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}